import ProjectDescription

let workspace = Workspace(
    name: "Pokedex",
    projects: ["./**"],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes:
                .enabled(codeCoverageMode: .targets([
                    "Pokedex",
                    "Backpack",
                    "Detail",
                    "Home",
                    "Catch",
                    "Common",
                    "Haneke",
                    "NetworkKit",
                    "UIComponents"]),
                         testingOptions: [])
    )
)

//testingOptions: [
//   .parallelizable,
//   .randomExecutionOrdering])
