# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.2.0

commands:
  restore_tuist_cache: 
    steps:
      - restore_cache:
          name: Restore ~/.tuist
          keys:
            - sources-{{ .Branch }}-{{ .Revision }}
            - sources-{{ .Branch }}-
            - sources-
  install_swiftlint:
    steps:
      - run:
          name: Install SwiftLint
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint 

  install_tuist:
    steps:
      - run:
          name: Installing Tuist
          command: |
            [ ! -f ~/.tuist/Versions/3.2.0/tuist ] && bash <(curl -Ls https://install.tuist.io) || echo "Skipping tuist install"
      - run:
          name: Install Tuist specific version
          command: |
            [ ! -f ~/.tuist/Versions/3.2.0/tuist ] && tuist install 3.2.0 || echo "Skipping tuist install version"
            
  setup_tuist:          
    steps: 
      - run: 
          name: Fetch Dependencies
          command: |
            [ -d Tuist/Dependencies/SwiftPackageManager/.build ] && echo "Skipping fetch" || ~/.tuist/Versions/3.2.0/tuist fetch 
      - run: 
          name: Tuist Cache Warm
          command: ~/.tuist/Versions/3.2.0/tuist cache warm -x

  run_tests:
    steps:
      - run: 
          name: Run Tuist Pokedex Tests  
          command: ~/.tuist/Versions/3.2.0/tuist test
          
  save_tuist_cache: 
    steps: 
      - save_cache:
          name: Save ~/.tuist
          key: sources-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.tuist/Cache
            - ~/.tuist/Versions
            - ".git"
  
  save_dependencies_cache:
    steps:
      - save_cache:
          name: Save Dependencies
          key: dependencies-tuist-{{ checksum "Tuist/Dependencies.swift" }}-{{ checksum "Tuist/Dependencies/Lockfiles/Package.resolved" }}
          paths: 
            - Tuist/Dependencies

  restore_dependencies_cache:
    steps:
      - restore_cache:
          name: Restore Dependencies
          keys: 
            - dependencies-tuist-{{ checksum "Tuist/Dependencies.swift" }}-{{ checksum "Tuist/Dependencies/Lockfiles/Package.resolved" }}
            - dependencies-tuist-{{ checksum "Tuist/Dependencies.swift" }}
            - dependencies-tuist-

  find_builds:
    steps:
      - run:
          name: Find build
          command: ls -latrp ~/Library/Developer/Xcode/DerivedData

jobs:    
  build_and_test:
    macos: 
      xcode: 13.3.1
    steps:
      - restore_tuist_cache
      - checkout  
      - restore_dependencies_cache
      - install_swiftlint
      - install_tuist 
      - setup_tuist
      - run_tests
      - save_dependencies_cache
      - save_tuist_cache
      - find_builds

workflows: 
  test_workflow:
    jobs: 
      - build_and_test
