# .circleci/config.yml

version: 2.1

parameters:
  xcode_version:
    default: "13.2.1"
    type: string
  run-build-and-test-CatchUI:
    type: boolean
    default: false
  run-build-and-test-BackpackUI:
    type: boolean
    default: false
  run-build-and-test-DetailUI:
    type: boolean
    default: false
  run-build-and-test-HomeUI:
    type: boolean
    default: false
  run-build-and-test-Pokedex:
    type: boolean
    default: false

orbs:
  macos: circleci/macos@2.1.0
  path-filtering: circleci/path-filtering@0.1.1

commands:
  restore_tuist_cache:
    steps:
      - run:
          name: Create tuist checksum file
          command: find Project.swift Tuist -type f | xargs -P 2 shasum > Tuist.lock
      - restore_cache:
          name: Restore ~/.tuist
          keys:
            - source-tuist-{{ checksum "Tuist.lock" }}
            - source-tuist-
      #- run:
      #    name: Installing Tuist
      #    command: |
      #      bash <(curl -Ls https://install.tuist.io)
  setup_tuist_cache:
    steps: 
      - run: 
          name: Fetch Dependencies
          command: tuist-bin/tuist fetch  
      - run: 
          name: Tuist Cache Warm
          command: tuist-bin/tuist cache warm -x
      - run: 
          name: Tuist Generate Project
          command: tuist-bin/tuist generate -xn
      - save_cache:
          name: Save ~/.tuist
          key: source-tuist-{{ checksum "Tuist.lock" }}
          paths:
            - ~/.tuist/Cache
            - ~/.tuist/Versions

  run_tests_for_each_module:
    steps: 
      - run:
          name: Run Tuist Test Haneke
          command: tuist test Haneke --device "iPhone 11" --os 15.2 
      - run:
          name: Run Tuist Test NetworkingKit
          command: tuist test NetworkKit --device "iPhone 11" --os 15.2  
      - run:
          name: Run Tuist Test Common
          command: tuist test Common --device "iPhone 11" --os 15.2 
      - run:
          name: Run Tuist Test Home UI
          command: tuist test HomeUITests --device "iPhone 11" --os 15.2  
      - run:
          name: Run Tuist Test Catch UI
          command: tuist test CatchUITests --device "iPhone 11" --os 15.2  
      - run: 
          name: Run Tuist Test Backpack UI
          command: tuist test BackpackUITests --device "iPhone 11" --os 15.2 
      - run:
          name: Run Tuist Test Detail
          command: tuist test Detail --device "iPhone 11" --os 15.2 
      - run: 
          name: Run Tuist Pokedex Tests  
          command: tuist test Pokedex --device "iPhone 11" --os 15.2  

  run_tuist_tests: 
    steps: 
      - run: tuist-bin/tuist test

  build_example_apps:
    steps:
      - run: 
          name: Build Catch UI Example App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme CatchUIExampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -derivedDataPath ./derivedData
      - run:
          name: Build Home UI Example App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme HomeUIExampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -derivedDataPath ./derivedData
      - run: 
          name: Build Backpack UI Example App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme BackpackUIExampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -derivedDataPath ./derivedData
      - run: 
          name: Build Haneke Example App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme HanekeExampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -derivedDataPath ./derivedData
      - run: 
          name: Build Detail Example App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme DetailExampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -derivedDataPath ./derivedData
      - run: 
          name: Build NetworkKit Example App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme NetworkKitExampleApp -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -derivedDataPath ./derivedData
      - run: 
          name: Build Pokedex App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme Pokedex -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2' -derivedDataPath ./derivedData

jobs: 
  tuist_setup_and_cache: 
    macos:
      xcode: <<pipeline.parameters.xcode_version>>
    working_directory: /Users/distiller/project
    steps: 
      - checkout
      - restore_tuist_cache    
      - setup_tuist_cache
      - run: mv ".tuist-version" "tuist-version"
      - persist_to_workspace:
          root: .
          paths:
            - "Tuist.lock"
            - "Project.swift"
            - "Pokedex.xcodeproj/*"
            - "Pokedex.xcworkspace/*"
            - "Tuist/*"
            - "Derived/*"
            - "Features/*"
            - "scripts/*"
            - "tuist-bin/*"
            - "tuist-version"
          
      - save_cache:
          name: Save ~/.tuist
          key: source-tuist-{{ checksum "Tuist.lock" }}
          paths:
            - ~/.tuist/Cache

  build_modules: 
    macos: 
      xcode: <<pipeline.parameters.xcode_version>>
    # working_directory: /Users/distiller/project
    steps: 
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Restore all persisted workspace files
          command: |
              mv /tmp/workspace/* .
      - run: ls -la
      #- run:
      #    name: Installing Tuist
      #    command: |
      #      bash <(curl -Ls https://install.tuist.io)
      #- run:
      #    name: Create tuist checksum file
      #    command: find Project.swift Tuist -type f | xargs -P 2 shasum > Tuist.lock
      - restore_cache:
          name: Restore ~/.tuist
          keys:
            - source-tuist-{{ checksum "Tuist.lock" }}
            - source-tuist-{{ checksum ".tuist-version" }}
      - run: which tuist 
      - build_example_apps
      - run_tuist_tests
      # - run_tests_for_each_module
      - persist_to_workspace:
          root: .
          paths:
            - "derivedData/Build/Products/*"

  test_modules: 
    macos: 
      xcode: <<pipeline.parameters.xcode_version>>
    # working_directory: /Users/distiller/project
    steps: 
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Restore derivedData folder
          command: |
              mv /tmp/workspace/* .
      - run_tests_for_each_module
      
  build_test_all:
    macos: 
      xcode: <<pipeline.parameters.xcode_version>>
    steps:
      - checkout
      - retore_tuist_cache    
      - setup_tuist_cache
      - build_example_apps
      # - run_tests_for_each_module
      # - run: pwd
      - run_tuist_tests

workflows: 
  build-and-test:
    jobs: 
      #- build_test_all
      - tuist_setup_and_cache
      - build_modules:
         requires:
            - tuist_setup_and_cache
      # - test_modules:
      #    requires:
      #      - build_modules


  # build-and-test-backpack: 
  #  when: << pipeline.parameters.run-build-service-1-job >>
  #    - jobs: version
  #always_run:
   # jobs: 
  #    - path-filtering/filter:
  #      name: check-updated-files
  #      mapping: |
  #        Features/Detail/.* run-build-and-test-DetailUI true
  #        Features/Backpack/.* run-build-and-test-BackpackUI true
          
          # - tuist_install_cache
          # - tuist_test_modules

