# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.1.0

jobs: 
  build: 
    macos: 
      xcode: 13.2.1

    steps: 
      - checkout
      - run: 
          name: Install Tuist
          command: curl -Ls https://install.tuist.io | bash
      - run: 
          name: Fetch Dependencies
          command: tuist dependencies fetch   
      - run: 
          name: Tuist Generate Project
          command: tuist generate
      - run: 
          name: Tuist Build
          command: tuist build 
      - run: 
          name: Tuist Test
          command: tuist test --device "iPhone 11" --os 15.2

workflows: 
  build-project:
    jobs: 
      - build
