# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.1.0

jobs: 
  build: 
    macos: 
      xcode: 13.2.1

    steps: 
      - checkout
      - run: 
          name: Install Tuist
          command: curl -Ls https://install.tuist.io | bash
      - run: 
          name: Fetch Dependencies
          command: tuist dependencies fetch   
      - run: 
          name: Tuist Generate Project
          command: tuist generate
      - run: 
          name: Run Tuist Build
          command: tuist build 
      - run: 
          name: Run Tuist Test Backpack UI
          command: tuist test BackpackUITests --device "iPhone 11" --os 15.2
      - run:
          name: Run Tuist Test Catch UI
          command: tuist test CatchUITests --device "iPhone 11" --os 15.2  
      - run:
          name: Run Tuist Test Detail
          command: tuist test Detail --device "iPhone 11" --os 15.2 
      - run:
          name: Run Tuist Test Haneke
          command: tuist test Haneke --device "iPhone 11" --os 15.2 
      - run:
          name: Run Tuist Test Home UI
          command: tuist test HomeUITests --device "iPhone 11" --os 15.2 
      - run: 
          name: Run Tuist Pokedex Tests  
          command: tuist test Pokedex --device "iPhone 11" --os 15.2    

workflows: 
  build-project:
    jobs: 
      - build
