# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.2.0

commands:
  setup_tuist:
    steps:
      - run:
          name: Installing Tuist if not installed
          command: |
            bash <(curl -Ls https://install.tuist.io) 
      - run: 
          name: Fetch Dependencies
          command: tuist fetch
      - run: 
          name: Tuist Cache Warm
          command: tuist cache warm
      - run: 
          name: Tuist Generate Project
          command: tuist generate -n
  build_project:
    steps:
      - run: 
          name: Build Pokedex App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme Pokedex -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.2'
  run_tests:
    steps:
      - run: 
          name: Tuist test
          command: tuist test

jobs:    
  build_and_test:
    macos: 
      xcode: 13.3.1
    steps:
      - checkout   
      - setup_tuist
      - build_project
      - run_tests

workflows: 
  build_and_test_workflow:
    jobs: 
      - build_and_test
