# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.1.0

jobs: 
  build: 
    macos: 
      xcode: 13.2.1

    steps: 
      - checkout
      - run: gem install cocoapods
      - run: 
          name: Install Tuist
          command: curl -Ls https://install.tuist.io | bash
      - run: 
          name: Build Project
          command: xcodebuild -list

workflows: 
  build-project:
    jobs: 
      - build
