# .circleci/config.yml

version: 2.1

orbs:
  macos: circleci/macos@2.2.0

commands:
  install_swiftlint:
    steps:
      - run:
          name: Install SwiftLint
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint 
  install_tuist:
    steps:
      - run:
          name: Create tuist checksum file
          command: find Project.swift Tuist -type f | xargs -P 2 shasum > Tuist.lock
      - restore_cache:
          name: Restore ~/.tuist
          keys:
            - source-tuist-{{ checksum ".tuist-version" }}-{{ checksum "Tuist.lock" }}
            - source-tuist-{{ checksum ".tuist-version" }}
      - run:
          name: Installing Tuist
          command: |
            bash <(curl -Ls https://install.tuist.io)
  setup_tuist:
    steps: 
      - run: 
          name: Fetch Dependencies
          command: tuist fetch  
      - run: 
          name: Tuist Cache Warm
          command: tuist cache warm -x
      - run: 
          name: Tuist Generate Project
          command: tuist generate -xn
  build_project:
    steps:
      - run: 
          name: Build Pokedex App
          command: xcodebuild -workspace Pokedex.xcworkspace -scheme Pokedex -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.4'
  run_tests:
    steps:
      - run: 
          name: Run Tuist Pokedex Tests  
          command: tuist test
  save_tuist_cache: 
    steps: 
      - save_cache:
          name: Save ~/.tuist
          key: source-tuist-{{ checksum ".tuist-version" }}-{{ checksum "Tuist.lock" }}
          paths:
            - ~/.tuist/Cache
            - ~/.tuist/Versions
  save_dependencies_cache:
    steps:
      - save_cache:
          name: Save Dependencies
          key: dependencies-tuist-{{ checksum "Tuist/Dependencies.swift" }}
          paths: 
            - Tuist/Dependencies
  restore_dependencies_cache:
    steps:
      - restore_cache:
          name: Restore Dependencies
          keys: 
            - dependencies-tuist-{{ checksum "Tuist/Dependencies.swift" }}
            - dependencies-tuist-
jobs:    
  build_and_test:
    macos: 
      xcode: 13.3.1
    steps:
      - checkout  
      - install_swiftlint
      - install_tuist 
      - restore_dependencies_cache
      - setup_tuist
      - save_dependencies_cache
      - build_project
      - run_tests
      - save_tuist_cache

workflows: 
  build_and_test_workflow:
    jobs: 
      - build_and_test
